<?php
if ( ! defined( 'ABSPATH' ) ) exit;

function sfcfc_get_default_options() {
	return array(
		'cf_cache_enabled'   => 'on',
		'cf_always_online'   => 'on',
		'cf_development_mode' => '',
		'cf_crawler_hints'   => '',
		'cf_early_hints'     => '',
		'cf_rocket_loader'   => '',
		'cf_http3'           => 'on',
		'cf_zero_rtt'        => '',
		'cf_ip_geolocation'  => '',
		'cf_tls_1_3'         => 'on',
		'cf_browser_check'   => 'on',
		'cf_hotlink_protection' => '',
		'cf_ipv6'            => 'on',
		'cf_cache_level'     => 'aggressive',
		'cf_maxage'          => 604800,
		'cf_browser_maxage'  => 300,
		'cf_browser_ttl'     => '',
		'cf_edge_ttl'        => '',
		'purge_urls'         => '',
		'cache_exclude_urls' => '',
		'cache_exclude_cookies' => '',
		'cache_exclude_query_params' => '',
		'bypass_ajax'        => 'on',
		'bypass_rest_api'    => 'on',
		'purge_homepage_on_update' => 'on',
		'purge_homepage_on_trash'  => 'on',
		'purge_archives_on_update' => 'on',
		'purge_archives_on_trash'  => 'on',
		'purge_on_comment_approved' => '',
		'purge_on_comment_deleted'  => '',
		'purge_feeds'        => '',
		'purge_amp_urls'     => '',
		'auto_purge_html_only' => 'on',
		'auto_purge_whole'   => '',
		'dont_cache_for'     => array(
			'search' => 'on',
			'404'    => 'on',
		),
		'bypass_sitemap'     => 'on',
		'bypass_robots'      => 'on',
		'enable_preloader'   => '',
		'preloader_start_on_purge' => '',
		'preload_latest_posts' => '',
		'preload_sitemap'    => '',
		'preload_sitemap_paths' => '',
		'preloader_cronjob_enabled' => '',
		'remove_purge_toolbar' => '',
		'purge_min_role'     => 'administrator',
		'purge_roles'        => array(),
		'keep_data_on_uninstall' => '',
		'purge_on_theme_plugin_update' => 'on',
		'debug_logging'      => '',
		'enable_activity_log' => 'on',
		'remote_purge_url_enabled' => '',
	);
}
